# Generated by Django 2.2.5 on 2020-01-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='glimpse_text',
            field=models.TextField(default='Hello World'),
            preserve_default=False,
        ),
    ]
