# Generated by Django 2.2.5 on 2020-01-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200128_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='organization_slug',
            field=models.SlugField(default='juntos', max_length=250),
            preserve_default=False,
        ),
    ]
