# Generated by Django 2.2.5 on 2020-01-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_news_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlightedevents',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
    ]
