# Generated by Django 2.2.5 on 2020-01-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_jobapplication_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='organization_primary_objective1',
            field=models.CharField(default='We aim to help people', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='organization_primary_objective2',
            field=models.CharField(default='We are there to help', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='organization_primary_objective3',
            field=models.CharField(default='Hacking Homelesness', max_length=200),
            preserve_default=False,
        ),
    ]
